### ISSUE TITLE
prepare dataset

### ISSUE THREAD

**Issue by mokyjulo** [gorjanradevski/multimodal-distillation#2]
Hello, sir. Thank you for your work. I was thinking of applying this process to other datasets as well. Could you please explain how you prepared the datasets, assuming that the datasets are in raw video format? Are there any tools or labeling formats involved?

**Comment by gorjanradevski** [comment]
Sure, we'll do so by Friday next week. By then, we'll also update the README with a permanent download link to obtain the HDF5 files of the datasets and modalities we use in the paper.

**Comment by gorjanradevski** [comment]
I just pushed a "prototype" script which packs a video dataset to HDF5. Please feel free to modify the script as per your needs.
