### ISSUE TITLE
HDF5 files download

### ISSUE THREAD

**Issue by Westerby** [gorjanradevski/multimodal-distillation#4]
Dear Authors,
thank you very much for publishing your work. 
It looks like HDF5 files are no longer available on filesender website. Will you be able to share them again?
Thank you.

**Comment by Westerby** [comment]
I see in other comments, that HDF5 files are around 1TB... thats really large. I wanted to reproduce just part of the training on a sample of epic-kitchens, but it seems that relevant config files for this dataset are not on the repository?
Would it be possible for you to upload them?
Morover - do you concatenate all types of modalities (rgb, audio, flow) into one HDF5 file? If so, what is the order?

**Comment by gorjanradevski** [comment]
I’ll try to have the data (each modality separate HDF5 file) online again
by the end of the week. Sorry for the delay :)

**Comment by Westerby** [comment]
Cool, thank you very much:)

**Comment by richardchoism** [comment]
Hello, where can I download the data? I also don't need a whole dataset.

**Comment by gorjanradevski** [comment]
We cannot host the data permanently, please reach out via email and we'll forward you the data.
