### ISSUE TITLE
Download  HDF5 file

### ISSUE THREAD

**Issue by Jovie-Jiang** [gorjanradevski/multimodal-distillation#5]
Dear author, 
          thank you very much for publishing your work here, your code has made me gain a lot. 
          I'm very sorry that I found that the HDF5 file doesn't seem to be available anymore on the website you provided to download the dataset. Very presumptuous to bother you, can you please share it again?
          Thank you.

**Comment by gorjanradevski** [comment]
@Gin-jan please send me an email so that I can send you the HDF5 files, unfortunately I can't post them here at this moment.

**Comment by DongGeun123** [comment]
@gorjanradevski Can you send me the HDF5 file as well?? I sent you an e-mail

**Comment by zzz77772** [comment]
> Dear author, thank you very much for publishing your work here, your code has made me gain a lot. I'm very sorry that I found that the HDF5 file doesn't seem to be available anymore on the website you provided to download the dataset. Very presumptuous to bother you, can you please share it again? Thank you.
