### ISSUE TITLE
HDF5 file

### ISSUE THREAD

**Issue by richardchoism** [gorjanradevski/multimodal-distillation#6]
Hello author,

First, thanks for providing a code to the github.

I am trying to run the code but due to the lack of datasets which are in HDF5 format, I cannot execute the code.

Would it be possible to have the data wrapper code if the size of the data is too huge?

Thanks.

**Comment by gorjanradevski** [comment]
Currently sending you the data :).

**Comment by zzz77772** [comment]
Hello, I was wondering if you still have this data available? Would it be possible for you to share a copy with me? Thank you very much.
